####################################################################
# JEKYLL SITE SETTINGS
####################################################################
title: The Labhacker's Workshop
description: Resources for homelab hackers everywhere
remote_theme: athackst/jekyll-theme-profile
copyright: "Copyright &copy; 2024 Redeyed Technologies [<a href=\"https://www.labhacker.dev/about.html\">attributions</a>]"
url: "https://www.labhacker.dev"

####################################################################
# THEME DEFAULTS
####################################################################
defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
        image: /assets/img/default.png
        permalink: /blog/:categories/:title:output_ext
        toc: true

####################################################################
# THEME SETTINGS
####################################################################
style: appbar                                               # site style - one of 'appbar', 'topbar', 'sidebar', 'stacked'
# user_image:                                                 # user / project avatar.  If not set, the avatar of the project owner is used
dark_theme: dark                                            # theme to use for dark
light_theme: light                                          # theme to use for dark
# background:                                               # custom background image & overlay
#   image: /path/to.img
#   overlay: rgba(0, 0, 0, 0.7)
#   light:
#       overlay: rgba(255, 255, 255, 0.5)
#   dark:
#       overlay: rgba(0, 0, 0, 0.5)
# header:                                                   # custom header colours
#   color: "#4051b5"
#   text: "rgba(255, 255, 255, 0.7)"
#   accent: "#ffffff"
repo_info: false                                            # Show information for the source of this project
user_metadata: true                                         # Show metadata associated with the owner
profile_link: false                                         # Show link to owner's GitHub profile

####################################################################
# SOCIAL MEDIA SETTINGS
####################################################################
# icon_color: "#959da5"                                       # Colour of social media icons
social_media:                                               # Social media accounts
    # behance: your_username
    dev_to: ragdata
    # dribbble: your_username
    # docker: your_username
    # facebook: your_username
    github: labhackers
    # hackerrank: your_username
    # instagram: your_username
    # keybase: your_username
    # linkedin: your_username
    # mail: email@address
    # mastodon: your_username
    # medium: your_username
    # stackoverflow: your_user_id
    # telegram: your_username
    # threads: your_username
    # tiktok: your_username
    # unsplash: your_username
    # vk: your_username
    # vscode: althack
    # youtube: your_username
    # x: althack

####################################################################
# POST TIMELINE
####################################################################
posts_limit: 4                                              # number of posts to show on home page

####################################################################
# NAVIGATION LINKS
####################################################################
nav:
    - name: Home
      url: https://www.labhacker.dev/
    - name: About
      url: /about.html
    - name: Blog
      url: /blog
#    - name: Projects
#      url: /projects

####################################################################
# REPOSITORY LINKS
####################################################################
repositories:                                               # repositories to show on home page
    sort_by: pushed                                         # options: 'pushed', 'stars'
    limit: 6                                                # maximum number of repositories to show
    exclude:                                                # repositories to exclude
        archived: true
        forks: true
#         repositories:                                       # list of repositories to exclude
#             - item

####################################################################
# PLUGIN SETTINGS
####################################################################
plugins:
    - jekyll-remote-theme
    - jekyll-github-metadata
    - jekyll-relative-links
    - jekyll-paginate
    - jekyll-tagging

####################################################################
# JEKYLL-PAGINATE SETTINGS
####################################################################
paginate: 6                                                 # number of posts to show per page of blog posts
paginate_path: "/blog/page:num"

####################################################################
# JEKYLL-TAGGING SETTINGS
####################################################################
tag_page_layout: tags
tag_page_dir: tags
related_by: "tags or categories"

####################################################################
# JEKYLL-CATEGORY-PAGES SETTINGS
####################################################################
category_path: category
category_layout: category_layout.html

####################################################################
# CARD LINKS (moving to _data)
####################################################################
# links:
#     - name: Example
#       url: /path
#       thumbnail: /path/to.img
