title: The Labhacker's Workshop
description: Resources for homelab hackers everywhere
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: dark
logo: assets/img/LabHackers-256.png
favicon: true
show-credits: false
google_analytics:

platforms:
    - name: GitHub
      icon: <i class="fa-brands fa-github"></i>
      link: https://github.com/labhackers

plugins:
    - jekyll-remote-theme
