title: The Labhacker's Workshop
description: Resources for homelab hackers everywhere
remote_theme: athackst/jekyll-theme-profile
color-scheme: dark
logo: assets/img/LabHackers-256.png
favicon: true
hide_description: true
hide_project_page: true
hide_credits: true
google_analytics:

plugins:
    - jekyll-remote-theme
