####################################################################
# JEKYLL SITE SETTINGS
####################################################################
title: The Labhacker's Workshop
description: Resources for homelab hackers everywhere
remote_theme: athackst/jekyll-theme-profile
profile_link: true

####################################################################
# PLUGIN SETTINGS
####################################################################
plugins:
    - jekyll-remote-theme
    - jekyll-github-metadata
    - jekyll-relative-links
    - jekyll-paginate
    - jekyll-tagging
