name: Jekyll GH-Pages Tagging Workflow

on:
    push:
        branches:
            - master
        paths:
            - 'docs/_posts/*.md'
    workflow_dispatch:

jobs:
    generate_tags:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Generate Tags
              uses: ragdata/jekyll-ghpages-tagging@master
              with:
                posts_dir: "docs/_posts"
                tags_dir: "docs/_tags"
                tags_layout: "tags"
                feeds_dir: "docs/_feeds"
                feeds_layout: "feed"
              env:
                GITHUB_TOKEN: ${{ github.token }}
