name: Jekyll GH-Pages Tagging Workflow

on:
    push:
        branches:
            - master
        paths:
            - 'docs/_posts/*.md'
    workflow_dispatch:

jobs:
    call_reusable_workflow:
        permissions:
            contents: read
            pages: write
            id-token: write
        uses: ragdata/reusable-workflows/.github/workflows/jekyll-ghpages-tagging.yml@master
        with:
            posts_dir: "docs/_posts"
            tags_dir: "docs/_tags"
            tags_layout: "tags"
            feeds_dir: "docs/_feeds"
            feeds_layout: "feed"
        secrets:
            token: ${{ secrets.token }}
